[SYSTEM]
NEED_SIGN = false
NEED_ENCRYPT = false
LOCAL_TOKEN_NAME = 'aQCajMNF(64#KgQM3S!8li$MU9uSGHEo'
USER_TOKEN_NAME = '	z7$WT&5-*.HBONgdb90t$x-.c1D3krv7'
SERVER_TOKEN_NAME = 'z7$WT&5-*.H21e12$x-.cdsda1D3krv7'
ACTIVE_DISPLAY_NAME = '~b*,msrOgd-+uqawf4)Q(0$nDE4C72TI'
TOKEN_NAME = 'token'

THEME_NAME = 'x=2mu5jvMOa0YvzhBQA7eU(%uo7+-qT4'
LEFT_MENU_NAME = 'A4aS@j+^6~k!fcTHbQL&ZvoS#@,#2JA%'
