# 前端路由, 需要按模块分
MAIN_URL = '/'
NOT_FOUND_URL = '/404'

PROCESS_URL = '/process'
COMMAND_URL = '/command'
DIRECTORY_URL = '/directory'
NGINX_URL = '/nginx'

# 控制台
[DASHBOARD]
KEY = 'dashboard'
NAME = '控制台'
URL = '/'

# 服务器
[SERVER]
KEY = 'server'
NAME = '服务器'
URL = ''

[SERVER.LIST]
KEY = 'serverList'
NAME = '服务器列表'
URL = '/serverList'
DESCRIPTION = '集中管理服务器账号与访问信息'

[SERVER.DETAIL]
KEY = 'serverDetail'
NAME = '服务器详情'
URL = '/serverDetail'

# 持续交付
[PIPELINE]
KEY = 'pileline'
NAME = '持续交付'
URL = ''

[PIPELINE.LIST]
KEY = 'pipelineList'
NAME = '流水线'
URL = '/pipelineList'
DESCRIPTION = '可视化流水线，一键发布项目'

[PIPELINE.ADD]
KEY = 'pipelineAdd'
NAME = '流水线'
URL = '/pipelineAdd'

[PIPELINE.DETAIL]
KEY = 'pipelineDetail'
NAME = '流水线'
URL = '/pipelineDetail'

[PIPELINE.MARKET]
KEY = 'pipelineMarket'
NAME = '插件市场'
URL = '/pipelineMarket'
DESCRIPTION = '为流水线扩展更多自动化能力'

# 笔记
[NOTE]
KEY = 'note'
NAME = '笔记'
URL = ''

[NOTE.LIST]
KEY = 'noteList'
NAME = '文章记录'
URL = '/nodeList'
DESCRIPTION = '分类整理与沉淀知识与文章'

[NOTE.EDIT]
KEY = 'noteEdit'
NAME = '编辑笔记'
URL = '/nodeEdit'

[NOTE.DETAIL]
KEY = 'noteDetail'
NAME = '笔记详情'
URL = '/nodeDetail'

[NOTE.TAG]
KEY = 'noteTag'
NAME = '笔记标签'
URL = '/nodeTag'

[NOTE.TAGDETAIL]
KEY = 'noteTagDetail'
NAME = '笔记标签详情'
URL = '/nodeTagDetail'

[TOOLS]
KEY = 'tools'
NAME = '工具'
URL = ''

[TOOLS.FILELOOK]
KEY = 'quickLook'
NAME = '文件管理'
URL = '/quickLook'
DESCRIPTION = '统一查看与管理本地文件'

# 设置
[SETTING]
KEY = 'setting'
NAME = '设置'
URL = ''

[SETTING.SYSTEM]
KEY = 'system'
NAME = '偏好设置'
URL = '/system'

[MONITOR]
SERVER_URL = '/server'

[SDK]
[SDK.TRAY]
[SDK.TRAY.MENU]
KEY = 'trayMenu'
NAME = '托盘菜单'
URL = '/trayMenu'

# 答题
[ANSWER]
KEY = 'answer'
NAME = '信息记录'
URL = '/answer'
DESCRIPTION = '统一记录和管理各类网站信息'

# 机器人
[ROBOT]
KEY = 'robot'
NAME = '个人中枢'
URL = '/robot'
DESCRIPTION = '基于 Clawdbot 的自动化执行与协作能力'


